name: pr

on:
  pull_request:
  push:
    branches-ignore:
      - master

jobs:
  build_and_test:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Set up JDK 17
        uses: actions/setup-java@v2
        with:
          java-version: '17'
          distribution: 'temurin'
          cache: 'maven'
      - name: Build project with Maven
        run: mvn -T 4 --batch-mode -Djava.awt.headless=true verify -P enableTests
      - name: Run checkstyle
        run: mvn checkstyle:check
